# Constants and Enums for SparePro

USER_ROLE_ADMIN = 'admin'
USER_ROLE_MANAGER = 'manager'
USER_ROLE_EMPLOYEE = 'employee'
USER_ROLE_CUSTOMER = 'customer'

STAFF_ROLES = [USER_ROLE_ADMIN, USER_ROLE_MANAGER, USER_ROLE_EMPLOYEE]

USER_STATUS_ACTIVE = 'active'
USER_STATUS_INACTIVE = 'inactive'

ORDER_STATUS_PENDING = 'Pending'
ORDER_STATUS_CONFIRMED = 'Confirmed'
ORDER_STATUS_PROCESSING = 'Processing'
ORDER_STATUS_PACKED = 'Packed'
ORDER_STATUS_SHIPPED = 'Shipped'
ORDER_STATUS_DELIVERED = 'Delivered'
ORDER_STATUS_CANCELLED = 'Cancelled'

ORDER_STATUS_FLOW = [
    ORDER_STATUS_PENDING,
    ORDER_STATUS_CONFIRMED,
    ORDER_STATUS_PROCESSING,
    ORDER_STATUS_PACKED,
    ORDER_STATUS_SHIPPED,
    ORDER_STATUS_DELIVERED
]

PAYMENT_STATUS_PENDING = 'Pending'
PAYMENT_STATUS_PAID = 'Paid'
PAYMENT_STATUS_FAILED = 'Failed'
PAYMENT_STATUS_REFUNDED = 'Refunded'

PAYMENT_METHOD_COD = 'Cash on Delivery'

INVENTORY_TYPE_PURCHASE = 'Purchase'
INVENTORY_TYPE_SALE = 'Sale'
INVENTORY_TYPE_ADJUSTMENT = 'Adjustment'
INVENTORY_TYPE_RETURN = 'Return'
